Rules:
  - object_path: qc/ITS/.*
    delay: 240
    policy: 1_per_run
    delete_when_no_run: True
  - object_path: qc/TST_KEEP/.*
    delay: 240
    policy: 1_per_run
    delete_when_no_run: True
  - object_path: qc/.*       # Path in the CCDB to a certain object
    delay: 1440              # Delay in minutes during which a new object is not touched. (1 day)
    policy: 1_per_hour       # name of the policy to apply, must correspond to a python script.
  - object_path: QcCheck/.*
    delay: 60
    policy: 1_per_hour
  - object_path: Test
    delay: 240
    policy: none_kept
  - object_path: .*
    delay: 1440
    policy: skip
#  - object_path: no_cleanup/.*
#    delay: 60
#    policy: skip
#  - object_path: TRD_test/.*
#    delay: 60
#    policy: skip
#  - object_path: ZDC_test/.*
#    delay: 60
#    policy: skip
#  - object_path: ITSQcTask.*
#    delay: 60
#    policy: 1_per_hour
#  - object_path: Test/.*
#    delay: 60
#    policy: 1_per_hour
#  - object_path: ITSRAWDS.*
#    delay: 60
#    policy: 1_per_hour
#  - object_path: qc/MISC/QcTest1/.*
#    delay: 60
#    policy: 1_per_hour
#  - object_path: ITSQCTrhesholdTask/.*
#    delay: 60
#    policy: 1_per_hour
#  - object_path: .* # Path in the CCDB to a certain object
#    delay: 1440              # Delay in minutes during which a new object is not touched. (1 day)
#    policy: 1_per_hour       # name of the policy to apply, must correspond to a python script.
#  - object_path: QcTask/example
#    delay: 120
#    policy: 1_per_hour

Ccdb:
  Url: http://ccdb-test.cern.ch:8080
